server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /index.html {
    add_header Cache-Control "no-store" always;
  }

  location /api/ {
    proxy_pass http://postgrest:3000/;
    proxy_set_header Host $host;
  }

  location / {
    add_header Cache-Control "no-store" always;
    try_files $uri $uri/ /index.html;
  }
}
